# Importando as bibliotecas

In [ ]:
import pandas as pd
import plotly.express as px
import numpy as np


### -"Puxando" os DataFrames em csv
### -Juntando as colunas de data e hora
### -Criando uma coluna de "legenda"

In [2]:
df1A = pd.read_csv("21102200_A_20dez21.txt", delimiter = ",", header = 0, parse_dates=[['Date', 'Time']])
df1A['sistema'] = 'A'

df1B = pd.read_csv("21102200_B_20dez21.txt", delimiter = ",", header = 0, parse_dates=[['Date', 'Time']])
df1B['sistema'] = 'B'

df2A = pd.read_csv("21102200_A_11fev22.txt", delimiter = ",", header = 0, parse_dates=[['Date', 'Time']])
df2A['sistema'] = 'A'

df2B = pd.read_csv("21102200_A_11fev22.txt", delimiter = ",", header = 0, parse_dates=[['Date', 'Time']])
df2B['sistema'] = 'B'

# Concatenando cada DataFrame e visualizando

In [15]:
juntos = pd.concat([df1A, df2A, df1B, df2B])
print(juntos.shape, df1A.shape, df2A.shape, df1B.shape, df2B.shape)

(185435, 77) (42427, 77) (50301, 77) (42406, 77) (50301, 77)

# Como temos um número muito grande de colunas, vamos visualizar quais nos interessa e descartar as outras

In [14]:
juntos.dtypes

Date_Time                                         datetime64[ns]
unidox.common.project.starts_incept                        int64
unidox.common.project.runtime_incept                     float64
unidox.common.project.state_string                        object
unidox.common.project.mode_string                         object
unidox.common.project.net_dosage                         float64
unidox.setpoints.setpt_supply_pressure                     int64
unidox.setpoints.setpt_tank_level                          int64
unidox.setpoints.setpt_feedback_mode                     float64
unidox.setpoints.setpt_delivery_mode                       int64
unidox.setpoints.setpt_dosage_mode                         int64
unidox.setpoints.setpt_trim_mode                         float64
unidox.setpoints.setpt_pressure_mode                       int64
unidox.common.dissolution_pump1.status                    object
unidox.common.dissolution_pump1.speed_rpm                  int64
unidox.common.dissolution_pump1.power                    float64
unidox.common.dissolution_pump1.power_min                float64
unidox.common.dissolution_pump1.power_max                float64
unidox.common.dissolution_pump1.starts_incep               int64
unidox.common.dissolution_pump1.runtime_incept           float64
unidox.common.dissolution_pump2.status                    object
unidox.common.dissolution_pump2.speed_rpm                  int64
unidox.common.dissolution_pump2.power                    float64
unidox.common.dissolution_pump2.power_min                float64
unidox.common.dissolution_pump2.power_max                float64
unidox.common.dissolution_pump2.starts_incept              int64
unidox.common.dissolution_pump2.runtime_incept           float64
unidox.common.supply_pump.status                          object
unidox.common.supply_pump.frequency_cmd                    int64
unidox.common.supply_pump.power                          float64
                                                       ...
unidox.sdox.dissolved_oxygen.min                         float64
unidox.sdox.dissolved_oxygen.max                         float64
unidox.sdox.orp.value                                      int64
unidox.sdox.orp.min                                        int64
unidox.sdox.orp.max                                        int64
unidox.cdox.pH.value                                     float64
unidox.cdox.pH.min                                       float64
unidox.cdox.pH.max                                       float64
unidox.common.gas_regulator.command                        int64
unidox.common.liquid_flow.value                            int64
unidox.common.liquid_flow.min                              int64
unidox.common.liquid_flow.max                              int64
unidox.common.liquid_flow.totalizer_daily                  int64
unidox.common.liquid_flow.totalizer                        int64
unidox.common.liquid_temperature.value                     int64
unidox.common.liquid_temperature.min                       int64
unidox.common.liquid_temperature.max                       int64
unidox.common.process_flow.value                         float64
unidox.common.process_flow.min                           float64
unidox.common.process_flow.max                           float64
unidox.common.gas_flow.value                               int64
unidox.common.gas_flow.totalizer_daily                     int64
unidox.common.gas_flow.totalizer                           int64
unidox.common.gas_flow.min                                 int64
unidox.common.gas_flow.max                                 int64
unidox.common.gas_pressure.value                           int64
unidox.common.gas_pressure.min                             int64
unidox.common.gas_pressure.max                             int64
unidox.common.project.energy                               int64
sistema                                                   object
Length: 77, dtype: object

# Limpando o DataFrame removendo as colunas desnecessárias

In [6]:
juntos_limpo = juntos.drop(juntos.loc[:, 'unidox.common.project.mode_string':'unidox.common.process_flow.max'].columns, axis = 1)

# Renomeando as colunas utilizando um dicionário

In [16]:
dict = {'Date_Time': 'data_hora',
        'unidox.common.project.starts_incept': 'tempo_start',
        'unidox.common.project.runtime_incept': 'tempo_ligado',
        'unidox.common.project.state_string': 'status',
        'unidox.common.gas_flow.value': 'o2',
        'unidox.common.gas_flow.totalizer_daily': 'o2_total_dia',
        'unidox.common.gas_flow.totalizer': 'o2_total',
        'unidox.common.gas_flow.min': 'o2_min_dia',
        'unidox.common.gas_flow.max': 'o2_max_dia',
        'unidox.common.project.energy': 'energia_total'
       }

juntos_limpo.rename(columns=dict, inplace=True)

# Visualizando o novo DataFrame

In [20]:
display(juntos_limpo)

,data_hora,tempo_start,tempo_ligado,status,o2,o2_total_dia,o2_total,o2_min_dia,o2_max_dia,unidox.common.gas_pressure.value,unidox.common.gas_pressure.min,unidox.common.gas_pressure.max,energia_total,sistema
0,2021-11-09 09:35:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
1,2021-11-09 09:36:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
2,2021-11-09 09:37:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
3,2021-11-09 09:38:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
4,2021-11-09 09:39:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
5,2021-11-09 09:40:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
6,2021-11-09 09:41:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
7,2021-11-09 09:42:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
8,2021-11-09 09:43:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
9,2021-11-09 09:44:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
10,2021-11-09 09:45:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
11,2021-11-09 09:46:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
12,2021-11-09 09:47:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
13,2021-11-09 09:48:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
14,2021-11-09 09:49:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
15,2021-11-09 09:50:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
16,2021-11-09 09:51:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
17,2021-11-09 09:52:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
18,2021-11-09 09:53:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
19,2021-11-09 09:54:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
20,2021-11-09 09:55:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
21,2021-11-09 09:56:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
22,2021-11-09 09:57:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
23,2021-11-09 09:58:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
24,2021-11-09 09:59:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
25,2021-11-09 10:00:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
26,2021-11-09 10:01:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
27,2021-11-09 10:02:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
28,2021-11-09 10:03:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
29,2021-11-09 10:04:00,0,0.0,SHUTDOWN,0,0,0,0,0,0,0,0,15,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50271,2022-02-11 15:01:00,180,676.0,SHUTDOWN,0,7,70100,0,141,62,0,122,28226,B
50272,2022-02-11 15:02:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50273,2022-02-11 15:03:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50274,2022-02-11 15:04:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50275,2022-02-11 15:05:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50276,2022-02-11 15:06:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50277,2022-02-11 15:07:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50278,2022-02-11 15:08:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50279,2022-02-11 15:09:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50280,2022-02-11 15:10:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50281,2022-02-11 15:11:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50282,2022-02-11 15:12:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50283,2022-02-11 15:13:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50284,2022-02-11 15:14:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50285,2022-02-11 15:15:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50286,2022-02-11 15:16:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50287,2022-02-11 15:17:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50288,2022-02-11 15:18:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50289,2022-02-11 15:19:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50290,2022-02-11 15:20:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50291,2022-02-11 15:21:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50292,2022-02-11 15:22:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50293,2022-02-11 15:23:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50294,2022-02-11 15:24:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50295,2022-02-11 15:25:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50296,2022-02-11 15:26:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50297,2022-02-11 15:27:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50298,2022-02-11 15:28:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50299,2022-02-11 15:29:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B
50300,2022-02-11 15:30:00,180,676.0,SHUTDOWN,0,7,70100,0,141,61,0,122,28226,B

# Verificando se os "tipos" dos dados correspondem

In [10]:
juntos_limpo.dtypes

data_hora                           datetime64[ns]
tempo_start                                  int64
tempo_ligado                               float64
status                                      object
o2                                           int64
o2_total_dia                                 int64
o2_total                                     int64
o2_min_dia                                   int64
o2_max_dia                                   int64
unidox.common.gas_pressure.value             int64
unidox.common.gas_pressure.min               int64
unidox.common.gas_pressure.max               int64
energia_total                                int64
sistema                                     object
dtype: object

In [22]:
# CRIANDO O GRÁFICO
fig = px.histogram(
    juntos_limpo,
    x="data_hora",
    y="o2",
    color='sistema',
    text_auto=True,
    nbins=3000,
    histfunc="avg"
)
# CONFIGURAÇÃO DO EIXO X
# fig.update_xaxes(
#     showgrid=True,
#     ticklabelmode="period",
#     tickformat="%d\n%b-%Y",
#     dtick=172800000
# )

# CONFIGURAÇÃO DO EIXO Y
fig.update_yaxes(
    tick0=0,
    dtick=50)

# ADICIONANDO O BOTÕES E SLIDER
fig.update_layout(
     #bargap=1,
     xaxis=dict(
         rangeselector=dict(
             buttons=list([
                 dict(
                     count=7,
                     label="Semana",
                     step="day",
                     stepmode="backward"
                 ),
                 dict(
                     count=1,
                     label="Mês",
                     step="month",
                     stepmode="todate"
                 ),
                 dict(
                     count=2,
                     label="2 Meses",
                     step="month",
                     stepmode="backward"
                 ),
                 dict(
                     label="Tudo",
                     step="all"
                 )
             ])
         ),
         rangeslider=dict(
             autorange=True,
             visible=True,
             borderwidth=1
         ),
         type="date"
     )
)

fig.show()

TypeError: 'dict' object is not callable